-- =========================================================
-- DATABASE DDL FOR H2 - Music Store Database
-- =========================================================
-- Convención: Tablas y columnas en MAYÚSCULAS con SNAKE_CASE
-- Cada tabla con clave primaria numérica usa su propia secuencia
-- =========================================================

-- Secuencias para claves primarias
CREATE SEQUENCE IF NOT EXISTS SEQ_ARTIST_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ALBUM_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_GENRE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MEDIA_TYPE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_TRACK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PLAYLIST_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PLAYLIST_TRACK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EMPLOYEE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CUSTOMER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE_LINE_ID START WITH 1 INCREMENT BY 1;

-- Tabla: ARTISTS
CREATE TABLE IF NOT EXISTS ARTISTS (
    ARTIST_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_ARTIST_ID,
    NAME VARCHAR(120) NOT NULL,
    PRIMARY KEY (ARTIST_ID)
);

-- Índice para búsquedas por nombre de artista
CREATE INDEX IF NOT EXISTS IDX_ARTISTS_NAME ON ARTISTS(NAME);

-- Tabla: GENRES
CREATE TABLE IF NOT EXISTS GENRES (
    GENRE_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_GENRE_ID,
    NAME VARCHAR(120) NOT NULL,
    PRIMARY KEY (GENRE_ID)
);

-- Índice para búsquedas por nombre de género
CREATE INDEX IF NOT EXISTS IDX_GENRES_NAME ON GENRES(NAME);

-- Tabla: MEDIA_TYPES
CREATE TABLE IF NOT EXISTS MEDIA_TYPES (
    MEDIA_TYPE_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_MEDIA_TYPE_ID,
    NAME VARCHAR(120) NOT NULL,
    PRIMARY KEY (MEDIA_TYPE_ID)
);

-- Índice para búsquedas por nombre de media type
CREATE INDEX IF NOT EXISTS IDX_MEDIA_TYPES_NAME ON MEDIA_TYPES(NAME);

-- Tabla: ALBUMS
CREATE TABLE IF NOT EXISTS ALBUMS (
    ALBUM_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_ALBUM_ID,
    TITLE VARCHAR(160) NOT NULL,
    ARTIST_ID INTEGER NOT NULL,
    PRIMARY KEY (ALBUM_ID),
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTIST_ID)
);

-- Índice para búsquedas por título de álbum
CREATE INDEX IF NOT EXISTS IDX_ALBUMS_TITLE ON ALBUMS(TITLE);
-- Índice para acelerar búsquedas combinadas por artista
CREATE INDEX IF NOT EXISTS IDX_ALBUMS_ARTIST ON ALBUMS(ARTIST_ID);

-- Tabla: TRACKS
CREATE TABLE IF NOT EXISTS TRACKS (
    TRACK_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_TRACK_ID,
    NAME VARCHAR(200) NOT NULL,
    ALBUM_ID INTEGER,
    MEDIA_TYPE_ID INTEGER NOT NULL,
    GENRE_ID INTEGER,
    COMPOSER VARCHAR(220),
    MILLISECONDS INTEGER,
    BYTES INTEGER,
    UNIT_PRICE DECIMAL(10,2),
    PRIMARY KEY (TRACK_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ALBUM_ID),
    FOREIGN KEY (MEDIA_TYPE_ID) REFERENCES MEDIA_TYPES(MEDIA_TYPE_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
);

-- Índices para búsqueda por nombre y combinaciones usadas en import
CREATE INDEX IF NOT EXISTS IDX_TRACKS_NAME ON TRACKS(NAME);
CREATE INDEX IF NOT EXISTS IDX_TRACKS_ALBUM ON TRACKS(ALBUM_ID);
CREATE INDEX IF NOT EXISTS IDX_TRACKS_GENRE ON TRACKS(GENRE_ID);
CREATE INDEX IF NOT EXISTS IDX_TRACKS_MEDIATYPE ON TRACKS(MEDIA_TYPE_ID);
-- Índice compuesto para findByNameAndAlbum
CREATE INDEX IF NOT EXISTS IDX_TRACKS_NAME_ALBUM ON TRACKS(NAME, ALBUM_ID);

-- Tabla: PLAYLISTS
CREATE TABLE IF NOT EXISTS PLAYLISTS (
    PLAYLIST_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_PLAYLIST_ID,
    NAME VARCHAR(120) NOT NULL,
    PRIMARY KEY (PLAYLIST_ID)
);

CREATE INDEX IF NOT EXISTS IDX_PLAYLISTS_NAME ON PLAYLISTS(NAME);
-- Unicidad lógica de nombre de artista
CREATE UNIQUE INDEX IF NOT EXISTS UQ_ARTISTS_NAME ON ARTISTS(NAME);
-- Tabla: PLAYLIST_TRACK (relación N:N con PK propia)
-- Unicidad de nombre de género
CREATE UNIQUE INDEX IF NOT EXISTS UQ_GENRES_NAME ON GENRES(NAME);
    PLAYLIST_TRACK_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_PLAYLIST_TRACK_ID,
-- Unicidad de nombre de media type
CREATE UNIQUE INDEX IF NOT EXISTS UQ_MEDIA_TYPES_NAME ON MEDIA_TYPES(NAME);
    TRACK_ID INTEGER NOT NULL,
-- Unicidad de nombre de playlist
CREATE UNIQUE INDEX IF NOT EXISTS UQ_PLAYLISTS_NAME ON PLAYLISTS(NAME);
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLIST_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(TRACK_ID)
-- Unicidad combinada título+artista (evita dos álbumes con mismo título para el mismo artista)
CREATE UNIQUE INDEX IF NOT EXISTS UQ_ALBUMS_TITLE_ARTIST ON ALBUMS(TITLE, ARTIST_ID);

-- Índice compuesto para existencia de relación playlist-track
CREATE INDEX IF NOT EXISTS IDX_PLAYLIST_TRACK_PLAYLIST_TRACK ON PLAYLIST_TRACK(PLAYLIST_ID, TRACK_ID);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
-- Unicidad combinada track name + album (evita duplicados exactos de un track dentro de un álbum)
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TRACKS_NAME_ALBUM ON TRACKS(NAME, ALBUM_ID);
    EMPLOYEE_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_EMPLOYEE_ID,
    LAST_NAME VARCHAR(20),
    FIRST_NAME VARCHAR(20),
    TITLE VARCHAR(30),
    REPORTS_TO INTEGER,
    BIRTH_DATE DATE,
    HIRE_DATE DATE,
    ADDRESS VARCHAR(70),
    CITY VARCHAR(40),
    STATE VARCHAR(40),
    COUNTRY VARCHAR(40),
    POSTAL_CODE VARCHAR(10),
    PHONE VARCHAR(24),
    FAX VARCHAR(24),
    EMAIL VARCHAR(60),
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Tabla: CUSTOMERS
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_CUSTOMER_ID,
    FIRST_NAME VARCHAR(40),
    LAST_NAME VARCHAR(20),
    COMPANY VARCHAR(80),
    ADDRESS VARCHAR(70),
    CITY VARCHAR(40),
    STATE VARCHAR(40),
    COUNTRY VARCHAR(40),
    POSTAL_CODE VARCHAR(10),
    PHONE VARCHAR(24),
    FAX VARCHAR(24),
    EMAIL VARCHAR(60),
    SUPPORT_REP_ID INTEGER,
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (SUPPORT_REP_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Tabla: INVOICES
CREATE TABLE IF NOT EXISTS INVOICES (
    INVOICE_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_INVOICE_ID,
    CUSTOMER_ID INTEGER NOT NULL,
    INVOICE_DATE DATE,
    BILLING_ADDRESS VARCHAR(70),
    BILLING_CITY VARCHAR(40),
    BILLING_STATE VARCHAR(40),
    BILLING_COUNTRY VARCHAR(40),
    BILLING_POSTAL_CODE VARCHAR(10),
    TOTAL DECIMAL(10,2),
    PRIMARY KEY (INVOICE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Tabla: INVOICE_ITEMS
CREATE TABLE IF NOT EXISTS INVOICE_ITEMS (
    INVOICE_LINE_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_INVOICE_LINE_ID,
    INVOICE_ID INTEGER NOT NULL,
    TRACK_ID INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2),
    QUANTITY INTEGER,
    PRIMARY KEY (INVOICE_LINE_ID),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(INVOICE_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(TRACK_ID)
);

-- =========================================================
-- Fin del DDL
-- =========================================================
